name: Bug Report
description: Report a bug or issue with the Blockbench MCP plugin
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report

        Thank you for reporting a bug! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: "When I call the create_texture tool with..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Open Blockbench
        2. Load the MCP plugin
        3. Call tool X with parameters Y
        4. Observe error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened? Include any error messages.
    validations:
      required: true

  - type: input
    id: blockbench-version
    attributes:
      label: Blockbench Version
      placeholder: "4.10.0"
    validations:
      required: true

  - type: input
    id: plugin-version
    attributes:
      label: MCP Plugin Version
      placeholder: "1.4.0"
    validations:
      required: true

  - type: input
    id: mcp-client
    attributes:
      label: MCP Client
      description: Which MCP client are you using?
      placeholder: "Claude Code, Cline, MCP Inspector, etc."
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Console Logs
      description: Any relevant console output from Blockbench (Help > Developer > Open Dev Tools)
      render: shell
    validations:
      required: false
